[package]
name = "blockchain"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
time = "0.1.44"
serde = "1.0.130"
serde_derive = "1.0.147"
serde_json = "1.0.70"
sha2 = "0.7.1"